=== a00908270/spot-framework/spot-core/src/main/resources/itemtypes.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified">

	<xs:element name="types">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="enum" type="EnumType" minOccurs="0"
					maxOccurs="unbounded" />
				<xs:element name="type" type="ItemType" minOccurs="0"
					maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>

	</xs:element>

	<xs:complexType name="EnumType">
		<xs:sequence>
			<xs:element name="description" type="xs:string" minOccurs="0"
				maxOccurs="1" />
			<xs:element name="value" type="EnumValue" minOccurs="0"
				maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="required" />
		<xs:attribute name="package" type="xs:string" use="required" />
	</xs:complexType>

	<xs:complexType name="EnumValue">
		<xs:attribute name="code" type="xs:string" use="required" />
		<xs:attribute name="value" type="xs:string" use="optional" />
	</xs:complexType>

	<xs:complexType name="ItemType">
		<xs:sequence>
			<xs:element name="description" type="xs:string" minOccurs="0"
				maxOccurs="1" />
			<xs:element name="properties" minOccurs="0" maxOccurs="1">
				<xs:annotation>
					<xs:documentation>
						Defines the list of item attributes.
					</xs:documentation>
				</xs:annotation>
				<xs:complexType>
					<xs:sequence>
						<xs:element name="property" type="Property" minOccurs="0"
							maxOccurs="unbounded" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>
					Defines the name of the item type.
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="package" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>
					Defines the java package of the item type.
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="extends" type="xs:string" default="Item">
			<xs:annotation>
				<xs:documentation>
					Defines the super class of the given type
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="abstract" type="xs:boolean">
			<xs:annotation>
				<xs:documentation>
					Defines if the item type is abstract.
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="typeCode" type="xs:string" use="optional">
			<xs:annotation>
				<xs:documentation>
					The internal code of the item type, used for
					storage and other internal functionality.
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="separateDeployment" type="xs:boolean"
			default="false">
			<xs:annotation>
				<xs:documentation>
					Defines if the persistence service should create a
					separate deployment "table" for the given type.
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>

	<xs:complexType name="DefaultValue" mixed="true">
		<xs:attribute name="value" use="optional" type="xs:string" />
	</xs:complexType>

	<xs:complexType name="Property">
		<xs:sequence>
			<xs:element name="datatype" type="DataType" minOccurs="1"
				maxOccurs="1" />
			<xs:element name="description" type="xs:string" minOccurs="0"
				maxOccurs="1" />
			<xs:element name="modifiers" type="Modifiers" minOccurs="0"
				maxOccurs="1" />
			<xs:element name="accessors" type="Accessors" minOccurs="0"
				maxOccurs="1" />
			<xs:element name="relation" type="Relation" minOccurs="0"
				maxOccurs="1" />
			<xs:element name="validators" type="Validators" minOccurs="0"
				maxOccurs="1" />
			<xs:element name="defaultValue" type="DefaultValue"
				minOccurs="0" maxOccurs="1" />
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>
					Defines the name of the property.
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>

	<xs:complexType name="DataType">
		<xs:sequence>
			<xs:element name="genericArgument" type="GenericArgument"
				minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attribute name="class" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>
					Defines the java class of the data type.
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>

	<xs:complexType name="GenericArgument">
		<xs:attribute name="class" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>
					Defines the java class of the generic argument.
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="wildcard" type="xs:boolean" use="optional"
			default="false">
			<xs:annotation>
				<xs:documentation>
					If true the resulting generic type will be of
					&gt;? extends Type>
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>

	<xs:complexType name="Validators">
		<xs:sequence>
			<xs:element name="validator" type="Validator" minOccurs="0"
				maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="Validator">
		<xs:sequence>
			<xs:element name="argument" type="ValidatorArgument"
				minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attribute name="javaClass" type="xs:string" use="required" />
	</xs:complexType>

	<xs:complexType name="ValidatorArgument">
		<xs:attribute name="name" use="required" />
		<xs:attribute name="numberValue" use="optional" />
		<xs:attribute name="stringValue" use="optional" />
	</xs:complexType>

	<xs:complexType name="Modifiers">
		<xs:attribute name="unique" type="xs:boolean" default="false">
			<xs:annotation>
				<xs:documentation>Defines if the property is part of the uniqueness
					criteria of the given type.
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="readable" type="xs:boolean" default="true">
			<xs:annotation>
				<xs:documentation>
					Defines if the property is readable.
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="writable" type="xs:boolean" default="true">
			<xs:annotation>
				<xs:documentation>
					Defines if the property is writable.
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="isReference" type="xs:boolean"
			default="false">
			<xs:annotation>
				<xs:documentation>
					Defines if the property is referenced from other
					types.
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="initial" type="xs:boolean" default="false">
			<xs:annotation>
				<xs:documentation>
					Defines if the property can only be written once
					on item creation.
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>

	<xs:complexType name="Accessors">
		<xs:attribute name="valueProvider" type="xs:string" use="optional">
			<xs:annotation>
				<xs:documentation>
					Defines the spring bean id that handles read and
					write access to the property.
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="getter" type="xs:boolean" default="true">
			<xs:annotation>
				<xs:documentation>
					Defines if a getter method should be generated for
					the given property.
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="setter" type="xs:boolean" default="true">
			<xs:annotation>
				<xs:documentation>
					Defines if a setter method should be generated for
					the given property.
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>

	<xs:complexType name="Relation">
		<xs:annotation>
			<xs:documentation>
				Defines the relation settings of the property.
			</xs:documentation>
		</xs:annotation>
		<xs:attribute name="type" type="RelationType" default="OneToMany">
			<xs:annotation>
				<xs:documentation>Defines the type of relation.</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="referencedType" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>Defines the referenced type's class.
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="mappedTo" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>Defines the referenced property name.
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="casacadeOnDelete" type="xs:boolean"
			default="false">
			<xs:annotation>
				<xs:documentation>Defines if deletion is cascaded for all referenced
					items.
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>

	<xs:simpleType name="RelationType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="OneToMany" />
			<xs:enumeration value="OneToOne" />
			<xs:enumeration value="ManyToMany" />
		</xs:restriction>
	</xs:simpleType>

</xs:schema>

=== a00908270/spot-framework/spot-cms-base/src/main/resources/cms-base-itemtypes.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<types xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="itemtypes.xsd">

	<!-- enums -->

	<enum name="HtmlLinkTarget" package="at.spot.itemtype.cms.enumeration">
		<description>Represents an HTML link target used.</description>
		<value code="BLANK" />
		<value code="SELF" />
		<value code="PARENT" />
		<value code="TOP" />
	</enum>

	<enum name="Orientation" package="at.spot.itemtype.cms.enumeration">
		<description>Defines the orientation, eg. for layouts.</description>
		<value code="TOP" />
		<value code="BOTTOM" />
		<value code="LEFT" />
		<value code="RIGHT" />
	</enum>

	<enum name="TemplateRenderEngine" package="at.spot.itemtype.cms.enumeration">
		<description>The render engine used to render cms items.</description>
		<value code="VELOCITY" />
		<value code="FREEMARKER" />
		<value code="JSP" />
	</enum>

	<!-- image media -->
	<type name="ImageMedia" extends="FileMedia" package="at.spot.core.model.media">
		<properties>
		</properties>
	</type>

	<!-- cms item types -->

	<type name="AbstractCmsItem" abstract="true" package="at.spot.itemtype.cms.model"
		extends="UniqueIdItem">
		<properties>
			<property name="catalog">
				<datatype class="Catalog" />
				<description>The content catalog of the item.</description>
				<modifiers unique="true" />
				<validators>
					<validator javaClass="javax.validation.constraints.NotNull" />
				</validators>
			</property>
			<property name="restrictions">
				<datatype class="java.util.List">
					<genericArgument class="CmsRestriction" />
				</datatype>
				<description>The restrictions evaluate if the current cms item should be rendered.</description>
			</property>
			<property name="onlyOneRestrictionMustApply">
				<datatype class="boolean" />
				<description>
					f set to true, only one restriction must evaluate to "show cms item" 
					for the item to be visible.
				</description>
			</property>
		</properties>
	</type>

	<type name="CmsRestriction" extends="AbstractCmsItem" package="at.spot.itemtype.cms.model">
		<properties>
			<property name="evaluator">
				<datatype class="java.lang.String" />
				<description>The spring bean id of the corresponding evaluator implementation.</description>
			</property>
			<property name="evaluatorScript">
				<datatype class="java.lang.String" />
				<description>The beanshell script that evaluates the cms item visibility.</description>
			</property>
		</properties>
	</type>

	<type name="AbstractCmsComponent" abstract="true" extends="AbstractCmsItem"
		package="at.spot.itemtype.cms.model">
		<properties>
			<property name="renderContextProvider">
				<datatype class="java.lang.String" />
				<description>
					The spring bean id of the context provider implementation.
				</description>
			</property>
			<property name="renderContextPreparationScript">
				<datatype class="java.lang.String" />
				<description>
					Beanshell code that is executed before the page rendering.
					It can be used to prepare the render context variables.
				</description>
			</property>
			<property name="content">
				<datatype class="java.lang.String" />
			</property>
			<property name="renderEngine">
				<datatype class="TemplateRenderEngine" />
				<validators>
					<validator javaClass="javax.validation.constraints.NotNull" />
				</validators>
			</property>
		</properties>
	</type>

	<type name="AbstractCmsContainerComponent" abstract="true"
		extends="AbstractCmsComponent" package="at.spot.itemtype.cms.model">
		<properties>
			<property name="contentSlots">
				<datatype class="java.util.List">
					<genericArgument class="ContentSlot" />
				</datatype>
			</property>
		</properties>
	</type>

	<type name="CmsComponent" extends="AbstractCmsComponent" package="at.spot.itemtype.cms.model">
		<properties>
		</properties>
	</type>

	<type name="ContentSlot" extends="AbstractCmsItem" package="at.spot.itemtype.cms.model">
		<properties>
			<property name="cmsComponents">
				<datatype class="java.util.Map">
					<genericArgument class="java.lang.String" />
					<genericArgument class="CmsComponent" />
				</datatype>
			</property>
		</properties>
	</type>

	<type name="CmsPageTemplate" extends="AbstractCmsContainerComponent"
		package="at.spot.itemtype.cms.model">
		<properties>
			<property name="title">
				<datatype class="at.spot.core.infrastructure.type.LocalizedString" />
			</property>
			<property name="favIconPath">
				<datatype class="at.spot.core.infrastructure.type.LocalizedString" />
			</property>
			<property name="favIcon">
				<datatype class="ImageMedia" />
			</property>
			<property name="metaTags">
				<datatype class="java.util.Map">
					<genericArgument class="java.lang.String" />
					<genericArgument class="at.spot.core.infrastructure.type.LocalizedString" />
				</datatype>
			</property>
		</properties>
	</type>

	<type name="CmsPage" extends="CmsPageTemplate" package="at.spot.itemtype.cms.model">
		<properties>
			<property name="urlMatches">
				<datatype class="java.util.List">
					<genericArgument class="java.lang.String" />
				</datatype>
				<description>Holds the regex string to determine which URL should be handler by this page.</description>
			</property>
			<property name="template">
				<datatype class="CmsPageTemplate" />
			</property>
		</properties>
	</type>

	<!-- special cms components -->

	<type name="AbstractNavigationEntry" abstract="true" extends="CmsComponent"
		package="at.spot.itemtype.cms.model">
		<properties>
			<property name="name">
				<datatype class="java.lang.String" />
				<description>The navigation entry name.</description>
			</property>
		</properties>
	</type>

	<type name="NavigationLinkEntry" extends="AbstractNavigationEntry"
		package="at.spot.itemtype.cms.model">
		<properties>
			<property name="href">
				<datatype class="java.lang.String" />
				<description>The href of the link.</description>
			</property>
			<property name="target">
				<datatype class="HtmlLinkTarget" />
				<description>The HTML link target.</description>
			</property>
		</properties>
	</type>

	<type name="AbstractNavigationContainer" abstract="true"
		package="at.spot.itemtype.cms.model">
		<properties>
			<property name="entries">
				<datatype class="java.util.List">
					<genericArgument class="NavigationLinkEntry" />
				</datatype>
				<description>A list of all navigation link.</description>
			</property>
		</properties>
	</type>

	<type name="NavigationBar" extends="AbstractNavigationContainer"
		package="at.spot.itemtype.cms.model" />

	<type name="Footer" extends="AbstractNavigationContainer" package="at.spot.itemtype.cms.model" />

</types>

=== a00908270/spot-framework/spot-core/resource/core-itemtypes.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<types xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="itemtypes.xsd">

	<type name="Principal" abstract="true" package="at.spot.core.model.user">
		<description>The base type all user related item types.</description>
		<properties>
			<property name="uid" class="java.lang.String">
				<description>The unique id of the principal object.</description>
				<modifiers unique="true" />
			</property>
			<property name="shortName" class="java.lang.String">
				<description>The short name identifying the principal object.
				</description>
			</property>
		</properties>
	</type>

	<type name="User" typeCode="User" extends="Principal"
		package="at.spot.core.model.user">
		<properties>
			<property name="password" class="java.lang.String">
				<description>The login password, can be encrypted.</description>
				<accessors getter="true" setter="true" field="false" />
			</property>
			<property name="emailAddress" class="java.lang.String">
				<description>The main email address of the user.</description>
			</property>
		</properties>
	</type>

	<type name="Product" typeCode="Product" package="at.spot.commerce.catalog">
		<description>The base type Product is used for all purchasable items.
		</description>
		<properties>
			<property name="code" class="java.lang.String">
				<description>The unique code of the product.</description>
				<modifiers unique="true" />
			</property>
		</properties>
	</type>
</types>
