=== a00908270/spot-framework/spot-core-base-models/src/main/resources/itemtypes.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified">

	<xs:element name="types">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="atomic" type="AtomicType" minOccurs="0"
					maxOccurs="unbounded" />
				<xs:element name="enum" type="EnumType" minOccurs="0"
					maxOccurs="unbounded" />
				<xs:element name="type" type="ItemType" minOccurs="0"
					maxOccurs="unbounded" />
				<xs:element name="relation" type="RelationType"
					minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="BaseType" abstract="true">
		<xs:sequence>
			<xs:element name="description" type="xs:string" minOccurs="0"
				maxOccurs="1" />
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>
					Defines the name of the item type.
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>

	<xs:complexType name="BaseComplexType" abstract="true">
		<xs:complexContent>
			<xs:extension base="BaseType">
				<xs:attribute name="package" type="xs:string" use="required">
					<xs:annotation>
						<xs:documentation>
							Defines the java package of the item type.
						</xs:documentation>
					</xs:annotation>
				</xs:attribute>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="ElementCollectionType">
		<xs:complexContent>
			<xs:extension base="BaseType">
				<xs:attribute name="elementType" type="xs:string" use="required" />
				<xs:attribute name="collectionType" type="CollectionType"
					use="required" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="ElementMapType">
		<xs:complexContent>
			<xs:extension base="BaseType">
				<xs:attribute name="keyType" type="xs:string" use="required" />
				<xs:attribute name="valueType" type="xs:string" use="required" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="AtomicType">
		<xs:complexContent>
			<xs:extension base="BaseType">
				<xs:attribute name="className" type="xs:string" use="required" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="EnumType">
		<xs:complexContent>
			<xs:extension base="BaseComplexType">
				<xs:sequence>
					<xs:element name="value" type="EnumValue" minOccurs="0"
						maxOccurs="unbounded" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="EnumValue">
		<xs:attribute name="code" type="xs:string" use="required" />
		<xs:attribute name="value" type="xs:string" use="optional" />
	</xs:complexType>

	<xs:complexType name="ItemType">
		<xs:complexContent>
			<xs:extension base="BaseComplexType">
				<xs:sequence>
					<xs:element name="properties" minOccurs="0" maxOccurs="1">
						<xs:annotation>
							<xs:documentation>
								Defines the list of item attributes.
							</xs:documentation>
						</xs:annotation>
						<xs:complexType>
							<xs:sequence>
								<xs:element name="property" type="Property"
									minOccurs="0" maxOccurs="unbounded" />
							</xs:sequence>
						</xs:complexType>
					</xs:element>
				</xs:sequence>

				<xs:attribute name="extends" type="xs:string" default="Item">
					<xs:annotation>
						<xs:documentation>
							Defines the super class of the given type
						</xs:documentation>
					</xs:annotation>
				</xs:attribute>
				<xs:attribute name="abstract" type="xs:boolean">
					<xs:annotation>
						<xs:documentation>
							Defines if the item type is abstract.
						</xs:documentation>
					</xs:annotation>
				</xs:attribute>
				<xs:attribute name="typeCode" type="xs:string" use="optional">
					<xs:annotation>
						<xs:documentation>
							The internal code of the item type, used for
							storage and other internal functionality.
						</xs:documentation>
					</xs:annotation>
				</xs:attribute>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="DefaultValue" mixed="true">
		<xs:attribute name="value" use="optional" type="xs:string" />
	</xs:complexType>

	<xs:complexType name="Property">
		<xs:sequence>
			<xs:element name="description" type="xs:string" minOccurs="0"
				maxOccurs="1" />
			<xs:element name="modifiers" type="Modifiers" minOccurs="0"
				maxOccurs="1" />
			<xs:element name="accessors" type="Accessors" minOccurs="0"
				maxOccurs="1" />
			<xs:element name="validators" type="Validators" minOccurs="0"
				maxOccurs="1" />
			<xs:element name="defaultValue" type="DefaultValue"
				minOccurs="0" maxOccurs="1" />
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>
					Defines the name of the property.
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="type" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>
					Defines the type of the property
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>

	<xs:complexType name="Validators">
		<xs:sequence>
			<xs:element name="validator" type="Validator" minOccurs="0"
				maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="Validator">
		<xs:sequence>
			<xs:element name="argument" type="ValidatorArgument"
				minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
		<xs:attribute name="javaClass" type="xs:string" use="required" />
	</xs:complexType>

	<xs:complexType name="ValidatorArgument">
		<xs:attribute name="name" use="required" />
		<xs:attribute name="numberValue" use="optional" />
		<xs:attribute name="stringValue" use="optional" />
	</xs:complexType>

	<xs:complexType name="Modifiers">
		<xs:attribute name="unique" type="xs:boolean" default="false">
			<xs:annotation>
				<xs:documentation>Defines if the property is part of the uniqueness
					criteria of the given type.
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="readable" type="xs:boolean" default="true">
			<xs:annotation>
				<xs:documentation>
					Defines if the property is readable.
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="writable" type="xs:boolean" default="true">
			<xs:annotation>
				<xs:documentation>
					Defines if the property is writable.
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="initial" type="xs:boolean" default="false">
			<xs:annotation>
				<xs:documentation>
					Defines if the property can only be written once
					on item creation.
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>

	<xs:complexType name="Accessors">
		<xs:attribute name="valueProvider" type="xs:string" use="optional">
			<xs:annotation>
				<xs:documentation>
					Defines the spring bean id that handles read and
					write access to the property.
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="getter" type="xs:boolean" default="true">
			<xs:annotation>
				<xs:documentation>
					Defines if a getter method should be generated for
					the given property.
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="setter" type="xs:boolean" default="true">
			<xs:annotation>
				<xs:documentation>
					Defines if a setter method should be generated for
					the given property.
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>

	<xs:complexType name="RelationType">
		<xs:sequence>
			<xs:element name="description" type="xs:string" minOccurs="0"
				maxOccurs="1" />
			<xs:element name="source" type="RelationNode" minOccurs="1"
				maxOccurs="1" />
			<xs:element name="target" type="RelationNode" minOccurs="1"
				maxOccurs="1" />
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>
					Defines the name of the item type.
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>

	<xs:complexType name="RelationNode">
		<xs:sequence>
			<xs:element name="description" type="xs:string" minOccurs="0"
				maxOccurs="1" />
		</xs:sequence>
		<xs:attribute name="itemType" type="xs:string">
			<xs:annotation>
				<xs:documentation>Defines the itemtype of the relation endpoint.
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="mappedBy" type="xs:string" use="optional">
			<xs:annotation>
				<xs:documentation>
					Defines the name of the property that references
					this endpoint item type.
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="cardinality" type="RelationshipCardinality"
			use="required">
			<xs:annotation>
				<xs:documentation>
					Defines if the cardinality of the relation
					endpoint.
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="collectionType" type="xs:string">
			<xs:annotation>
				<xs:documentation>
					Defines the collection type of the property
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>

	<xs:simpleType name="RelationshipCardinality">
		<xs:restriction base="xs:string">
			<xs:enumeration value="one" />
			<xs:enumeration value="many" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="RelationshipType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="OneToMany" />
			<xs:enumeration value="OneToOne" />
			<xs:enumeration value="ManyToMany" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="CollectionType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="List" />
			<xs:enumeration value="Set" />
			<xs:enumeration value="Collection" />
		</xs:restriction>
	</xs:simpleType>

</xs:schema>

=== a00908270/spot-framework/spot-archetype-simple/src/main/resources/sample-itemtypes.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<types xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://spot-next.io/schemas/v1/itemtypes.xsd">

	<!-- enums -->

	<enum name="UserType" package="io.spotnext.sample.itemtype.sample.enumeration">
		<value code="GUEST" />
		<value code="REGISTERED" />
	</enum>

	<bean name="UserData" package="io.spotnext.sample.itemtype.sample.beans">
		<properties>
			<property name="type" type="UserType">
				<validators>
					<validator javaClass="javax.validation.constraints.NotNull" />
				</validators>
			</property>
		</properties>
	</bean>

	<!-- users and groups -->

	<type name="User" package="io.spotnext.itemtype.core.user">
		<properties>
			<property name="type" type="UserType">
				<!-- <validators> -->
				<!-- <validator javaClass="javax.validation.constraints.NotNull" /> -->
				<!-- </validators> -->
			</property>
		</properties>
	</type>

</types>

=== a00908270/spot-framework/spot-commerce-base/src/main/resources/commerce-base-itemtypes.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<types xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="itemtypes.xsd">

	<type name="Product" typeCode="Product" package="at.spot.commerce.catalog">
		<description>The base type Product is used for all purchasable items.</description>
		<properties>
			<property name="code">
				<datatype class="java.lang.String" />
				<description>The unique product code.</description>
				<modifiers unique="true" />
				<validators>
					<validator javaClass="javax.validation.constraints.NotNull" />
				</validators>
			</property>
		</properties>
	</type>
</types>

=== a00908270/spot-framework/spot-sample-spring-mvc/src/main/resources/sample-itemtypes.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<types xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="http://spot-next.io/schemas/v1/itemtypes.xsd">

	<!-- enums -->

	<enum name="UserType" package="io.spotnext.sample.types.enumerations">
		<value code="GUEST" />
		<value code="REGISTERED" />
	</enum>

	<bean name="UserData" package="io.spotnext.sample.types.beans">
		<properties>
			<property name="type" type="UserType">
				<validators>
					<validator javaClass="javax.validation.constraints.NotNull" />
				</validators>
			</property>
		</properties>
	</bean>

	<!-- users and groups -->

	<type name="User" package="io.spotnext.itemtype.core.user">
		<properties>
			<property name="type" type="UserType">
				<validators>
					<validator javaClass="javax.validation.constraints.NotNull" />
				</validators>
				<defaultValue>io.spotnext.sample.types.enumerations.UserType.REGISTERED
				</defaultValue>
			</property>
		</properties>
	</type>
	
	<type name="Party" package="io.spotnext.sample.types.itemtypes">
		<properties>
			<property name="title" type="String">
				<description>The unique title of the party</description>
				<modifiers unique="true" />
				<validators>
					<validator javaClass="javax.validation.constraints.NotNull" />
				</validators>
			</property>
			<property name="motto" type="LocalizedString" localized="true">
				<description>The localized motto of the party</description>
			</property>
			<property name="location" type="Address">
				<description>The location the party will take place</description>
			</property>
			<property name="date" type="Date">
				<description>The date the party will take place</description>
			</property>
			<property name="fixed" type="boolean">
				<description>Defines that the party has been fixed and should not be changed anymore.</description>
				<defaultValue>false</defaultValue>
			</property>
		</properties>
	</type>

	<relation name="Party2InvitedUser">
		<source itemType="Party" mappedBy="parties" cardinality="many">
			<description>The parties this user is invited.</description>
		</source>
		<target itemType="User" mappedBy="invitedGuests" cardinality="many">
			<description>The guests that are invited to this party.</description>
		</target>
	</relation>

</types>
